"""Tests for the HTML fragments generated by build.py."""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import build  # noqa: E402


def make_article(**overrides: object) -> dict:
    article = {
        "title": "A study of worms",
        "authors": "A Smith, MA Qureshi, B Jones",
        "venue": "Biology Open 10 (5), 2021",
        "year": "2021",
        "citations": 8,
        "link": "https://example.org/paper",
    }
    article.update(overrides)
    return article


# ── Publications ───────────────────────────────────────────────


def test_linked_pub_renders_stretched_title_link_and_arrow() -> None:
    html = build.build_publications_html([make_article()])
    assert 'class="pub-item has-link"' in html
    assert '<a class="pub-link" href="https://example.org/paper" target="_blank" rel="noopener">' in html
    assert 'class="pub-arrow"' in html
    # The separate "View" link is gone — the whole row is the link now.
    assert 'class="pub-doi"' not in html


def test_unlinked_pub_has_no_link_or_arrow() -> None:
    html = build.build_publications_html([make_article(link="")])
    assert 'class="pub-item"' in html
    assert "has-link" not in html
    assert "pub-link" not in html
    assert "pub-arrow" not in html


def test_zero_citations_omits_citation_span() -> None:
    html = build.build_publications_html([make_article(citations=None)])
    assert "pub-citations" not in html
    assert "pub-meta" not in html


def test_citation_count_pluralises() -> None:
    assert "1 citation<" in build.build_publications_html([make_article(citations=1)])
    assert "8 citations<" in build.build_publications_html([make_article(citations=8)])


def test_empty_venue_omits_venue_paragraph() -> None:
    html = build.build_publications_html([make_article(venue="")])
    assert "pub-venue" not in html


def test_title_venue_and_link_are_escaped() -> None:
    html = build.build_publications_html(
        [make_article(title="Worms <b>&</b> more", venue="J & K", link='https://x.org/?a=1&b="2"')]
    )
    assert "Worms &lt;b&gt;&amp;&lt;/b&gt; more" in html
    assert "<em>J &amp; K</em>" in html
    assert 'href="https://x.org/?a=1&amp;b=&quot;2&quot;"' in html


def test_year_is_escaped() -> None:
    html = build.build_publications_html([make_article(year="2021<script>")])
    assert "<script>" not in html
    assert '<div class="pub-year">2021&lt;script&gt;</div>' in html


def test_authors_are_escaped_then_bolded() -> None:
    html = build.format_authors("A <Smith>, MA Qureshi")
    assert html == "A &lt;Smith&gt;, <strong>MA Qureshi</strong>"


def test_generic_cover_uses_article_label() -> None:
    assert build.get_journal_cover("") == ("generic", "Article", "")
    assert build.get_journal_cover("Unknown Proceedings") == ("generic", "Article", "")


# ── Curated peer-reviewed list ─────────────────────────────────


def test_curated_papers_take_citations_and_authors_from_scholar() -> None:
    curated = [{"title": "A Study of Worms", "year": "2021", "venue": "Biology Open", "doi": "10.1242/BIO.1"}]
    scholar = [make_article(title="A study of worms", citations=42, authors="X Li, MA Qureshi")]
    pubs = build.merge_curated_publications(curated, scholar)
    assert len(pubs) == 1
    assert pubs[0]["citations"] == 42
    assert pubs[0]["authors"] == "X Li, MA Qureshi"
    assert pubs[0]["venue"] == "Biology Open 10 (5), 2021"  # Scholar's fuller venue string
    assert pubs[0]["link"] == "https://doi.org/10.1242/bio.1"  # DOI beats the Scholar link


def test_curated_paper_missing_from_scholar_is_still_listed() -> None:
    curated = [{"title": "Brand new paper", "year": "2026", "venue": "Nature Aging", "doi": "10.1/x"}]
    pubs = build.merge_curated_publications(curated, [make_article()])
    assert pubs == [{
        "title": "Brand new paper", "year": "2026", "venue": "Nature Aging",
        "authors": "", "citations": 0, "link": "https://doi.org/10.1/x",
    }]


def test_title_matching_ignores_case_punctuation_and_truncation() -> None:
    curated = [{"title": "The mitochondrial unfolded protein response: Signaling from the powerhouse", "year": "2017"}]
    scholar = [make_article(title="The mitochondrial unfolded protein response signaling from the", citations=179)]
    assert build.merge_curated_publications(curated, scholar)[0]["citations"] == 179


def test_curated_papers_sorted_newest_first() -> None:
    curated = [{"title": "Old", "year": "2017"}, {"title": "New", "year": "2026"}, {"title": "Mid", "year": "2021"}]
    assert [p["title"] for p in build.merge_curated_publications(curated, [])] == ["New", "Mid", "Old"]


def test_curated_list_is_not_truncated_to_eight() -> None:
    curated = [{"title": f"Paper {i}", "year": str(2000 + i)} for i in range(10)]
    html = build.render_publications_html(build.merge_curated_publications(curated, []))
    assert html.count("<li ") == 10


# ── Metrics ────────────────────────────────────────────────────


def test_metrics_strip_has_three_groups_with_live_numbers() -> None:
    html = build.build_metrics_html({"citations": 259}, pub_count=9)
    assert html.count('class="metric-group"') == 3
    for label in ("Industry", "Academic", "Federal"):
        assert f'<span class="metric-group-label">{label}</span>' in html
    assert 'data-target="259">259<' in html
    assert 'data-target="9">9<' in html
    # Counter JS depends on these hooks.
    assert html.count('class="metric-number"') == 6


def test_metrics_labels_name_their_sources() -> None:
    html = build.build_metrics_html({"citations": 275}, pub_count=6, pub_label="Peer-reviewed papers")
    assert '<span class="metric-label">Peer-reviewed papers</span>' in html
    assert '<span class="metric-label">Scholar citations</span>' in html
