"""Tests for the HTML fragments generated by build.py."""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import build  # noqa: E402


def make_article(**overrides: object) -> dict:
    article = {
        "title": "A study of worms",
        "authors": "A Smith, MA Qureshi, B Jones",
        "venue": "Biology Open 10 (5), 2021",
        "year": "2021",
        "citations": 8,
        "link": "https://example.org/paper",
    }
    article.update(overrides)
    return article


# ── Publications ───────────────────────────────────────────────


def test_linked_pub_renders_stretched_title_link_and_arrow() -> None:
    html = build.build_publications_html([make_article()])
    assert 'class="pub-item has-link"' in html
    assert '<a class="pub-link" href="https://example.org/paper" target="_blank" rel="noopener">' in html
    assert 'class="pub-arrow"' in html
    # The separate "View" link is gone — the whole row is the link now.
    assert 'class="pub-doi"' not in html


def test_unlinked_pub_has_no_link_or_arrow() -> None:
    html = build.build_publications_html([make_article(link="")])
    assert 'class="pub-item"' in html
    assert "has-link" not in html
    assert "pub-link" not in html
    assert "pub-arrow" not in html


def test_zero_citations_omits_citation_span() -> None:
    html = build.build_publications_html([make_article(citations=None)])
    assert "pub-citations" not in html
    assert "pub-meta" not in html


def test_citation_count_pluralises() -> None:
    assert "1 citation<" in build.build_publications_html([make_article(citations=1)])
    assert "8 citations<" in build.build_publications_html([make_article(citations=8)])


def test_empty_venue_omits_venue_paragraph() -> None:
    html = build.build_publications_html([make_article(venue="")])
    assert "pub-venue" not in html


def test_title_venue_and_link_are_escaped() -> None:
    html = build.build_publications_html(
        [make_article(title="Worms <b>&</b> more", venue="J & K", link='https://x.org/?a=1&b="2"')]
    )
    assert "Worms &lt;b&gt;&amp;&lt;/b&gt; more" in html
    assert "<em>J &amp; K</em>" in html
    assert 'href="https://x.org/?a=1&amp;b=&quot;2&quot;"' in html


def test_year_is_escaped() -> None:
    html = build.build_publications_html([make_article(year="2021<script>")])
    assert "<script>" not in html
    assert '<div class="pub-year">2021&lt;script&gt;</div>' in html


def test_authors_are_escaped_then_bolded() -> None:
    html = build.format_authors("A <Smith>, MA Qureshi")
    assert html == "A &lt;Smith&gt;, <strong>MA Qureshi</strong>"


def test_generic_cover_uses_article_label() -> None:
    assert build.get_journal_cover("") == ("generic", "Article", "")
    assert build.get_journal_cover("Unknown Proceedings") == ("generic", "Article", "")


# ── Metrics ────────────────────────────────────────────────────


def test_metrics_strip_has_three_groups_with_live_numbers() -> None:
    html = build.build_metrics_html({"citations": 259}, pub_count=9)
    assert html.count('class="metric-group"') == 3
    for label in ("Industry", "Academic", "Federal"):
        assert f'<span class="metric-group-label">{label}</span>' in html
    assert 'data-target="259">259<' in html
    assert 'data-target="9">9<' in html
    # Counter JS depends on these hooks.
    assert html.count('class="metric-number"') == 6
